/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /** Health check */
    get: {
      responses: {
        /** @description Server is healthy */
        200: {
          content: never;
        };
      };
    };
  };
  "/auth/login": {
    /** Login user */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Successful login — returns JWT token and user info */
        200: {
          content: never;
        };
        /** @description Invalid credentials */
        401: {
          content: never;
        };
        /** @description Account deactivated */
        403: {
          content: never;
        };
      };
    };
  };
  "/auth/me": {
    /** Get current user profile */
    get: {
      responses: {
        /** @description Authenticated user profile returned */
        200: {
          content: never;
        };
        /** @description Not authenticated */
        401: {
          content: never;
        };
      };
    };
  };
  "/auth/register": {
    /** Register new user (Admin only) */
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            role: string;
          };
        };
      };
      responses: {
        /** @description User registered successfully */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/incidents": {
    /** List incidents (paginated) */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
          /** @description Search term (filters by title/description) */
          search?: string;
          /** @description Filter by status */
          status?: "Open" | "In Progress" | "Acknowledged" | "Resolved" | "Closed";
          /** @description Filter by severity */
          severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
          /** @description Filter by system ID */
          systemId?: string;
          /** @description Filter by assigned user */
          assignedToId?: string;
          /** @description Sort field */
          sortBy?: string;
          /** @description Sort direction */
          sortOrder?: "asc" | "desc";
        };
      };
      responses: {
        /** @description Paginated list of incidents */
        200: {
          content: never;
        };
      };
    };
    /** Create new incident */
    post: {
      requestBody: {
        content: {
          "application/json": {
            title: string;
            description?: string;
            /** @enum {string} */
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            environment?: string;
            systemId: string;
            sysout?: string;
            assignedToId?: string;
          };
        };
      };
      responses: {
        /** @description Incident created */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/incidents/stats": {
    /** Get incident statistics for dashboard */
    get: {
      parameters: {
        query?: {
          /** @description Number of days for trend data */
          days?: number;
        };
      };
      responses: {
        /** @description Statistics returned (createdToday, resolvedToday, activeIncidents, avgResolutionTime, trend, topSystems) */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/incidents/search": {
    /** Search similar incidents */
    get: {
      parameters: {
        query: {
          /** @description Search query string */
          query: string;
        };
      };
      responses: {
        /** @description Search results */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/incidents/{id}": {
    /** Get incident details */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Incident details with logs, files, and linked procedures */
        200: {
          content: never;
        };
        /** @description Incident not found */
        404: {
          content: never;
        };
      };
    };
    /** Update incident */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            title?: string;
            description?: string;
            severity?: string;
            environment?: string;
            assignedToId?: string;
            sysout?: string;
          };
        };
      };
      responses: {
        /** @description Incident updated */
        200: {
          content: never;
        };
      };
    };
    /** Delete incident */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Incident deleted */
        204: {
          content: never;
        };
      };
    };
  };
  "/api/v1/incidents/{id}/status": {
    /** Update incident status */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            status: "Open" | "In Progress" | "Acknowledged" | "Resolved" | "Closed";
            notes?: string;
          };
        };
      };
      responses: {
        /** @description Status updated */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/incidents/{id}/acknowledge": {
    /** Acknowledge an incident */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Incident acknowledged */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/incidents/{id}/logs": {
    /** Add incident log entry */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            logType: string;
            details: string;
          };
        };
      };
      responses: {
        /** @description Log entry added */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/incidents/{id}/upload": {
    /** Upload file to incident */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "multipart/form-data": {
            /**
             * Format: binary
             * @description Max 25MB. Allowed types — text, csv, json, xml, pdf, png, jpeg, gif, webp, zip, gzip, xlsx, docx
             */
            file?: string;
          };
        };
      };
      responses: {
        /** @description File uploaded */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/incidents/{id}/files/{filename}": {
    /** Download incident file */
    get: {
      parameters: {
        path: {
          id: string;
          filename: string;
        };
      };
      responses: {
        /** @description File stream */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/incidents/{id}/link-procedure/{procedureId}": {
    /** Link procedure to incident */
    post: {
      parameters: {
        path: {
          id: string;
          procedureId: string;
        };
      };
      responses: {
        /** @description Procedure linked */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/users": {
    /** List all users */
    get: {
      responses: {
        /** @description List of users */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/users/{id}": {
    /** Update user */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            name?: string;
            email?: string;
            roleId?: string;
            isActive?: boolean;
          };
        };
      };
      responses: {
        /** @description User updated */
        200: {
          content: never;
        };
      };
    };
    /** Delete user */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description User deleted */
        204: {
          content: never;
        };
      };
    };
  };
  "/api/v1/systems": {
    /** List all systems */
    get: {
      responses: {
        /** @description List of systems */
        200: {
          content: never;
        };
      };
    };
    /** Create system */
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            description?: string;
          };
        };
      };
      responses: {
        /** @description System created */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/systems/{id}": {
    /** Update system */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["System"];
        };
      };
      responses: {
        /** @description System updated */
        200: {
          content: never;
        };
      };
    };
    /** Delete system */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description System deleted */
        204: {
          content: never;
        };
      };
    };
  };
  "/api/v1/jobs": {
    /** List all jobs */
    get: {
      responses: {
        /** @description List of jobs */
        200: {
          content: never;
        };
      };
    };
    /** Create job */
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            code: string;
            systemId: string;
            teamId?: string;
          };
        };
      };
      responses: {
        /** @description Job created */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/jobs/{id}": {
    /** Update job */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Job"];
        };
      };
      responses: {
        /** @description Job updated */
        200: {
          content: never;
        };
      };
    };
    /** Delete job */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Job deleted */
        204: {
          content: never;
        };
      };
    };
  };
  "/api/v1/teams": {
    /** List all teams */
    get: {
      responses: {
        /** @description List of teams */
        200: {
          content: never;
        };
      };
    };
    /** Create team */
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            description?: string;
            emailDistribution?: string;
            isActive?: boolean;
            sendEmail?: boolean;
          };
        };
      };
      responses: {
        /** @description Team created */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/teams/{id}": {
    /** Get team details with members */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Team details */
        200: {
          content: never;
        };
      };
    };
    /** Update team */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Team"];
        };
      };
      responses: {
        /** @description Team updated */
        200: {
          content: never;
        };
      };
    };
    /** Delete team */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Team deleted */
        204: {
          content: never;
        };
      };
    };
  };
  "/api/v1/teams/{id}/members": {
    /** Add team member */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            userId: string;
            /** @description Role within the team (e.g., LEAD, MEMBER) */
            role?: string;
          };
        };
      };
      responses: {
        /** @description Member added */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/teams/{id}/members/{userId}": {
    /** Remove team member */
    delete: {
      parameters: {
        path: {
          id: string;
          userId: string;
        };
      };
      responses: {
        /** @description Member removed */
        204: {
          content: never;
        };
      };
    };
  };
  "/api/v1/slas": {
    /** List all SLAs */
    get: {
      responses: {
        /** @description List of SLAs */
        200: {
          content: never;
        };
      };
    };
    /** Create SLA */
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** @enum {string} */
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            acknowledgeTimeMinutes: number;
            resolveTimeMinutes: number;
          };
        };
      };
      responses: {
        /** @description SLA created */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/slas/{id}": {
    /** Get SLA details */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description SLA details */
        200: {
          content: never;
        };
      };
    };
    /** Update SLA */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["SLA"];
        };
      };
      responses: {
        /** @description SLA updated */
        200: {
          content: never;
        };
      };
    };
    /** Delete SLA */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description SLA deleted */
        204: {
          content: never;
        };
      };
    };
  };
  "/api/v1/procedures": {
    /** List/search procedures */
    get: {
      parameters: {
        query?: {
          /** @description Search term */
          search?: string;
        };
      };
      responses: {
        /** @description List of procedures */
        200: {
          content: never;
        };
      };
    };
    /** Create procedure */
    post: {
      requestBody: {
        content: {
          "application/json": {
            title: string;
            content: string;
            systemId?: string;
          };
        };
      };
      responses: {
        /** @description Procedure created */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/procedures/{id}": {
    /** Get procedure details */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Procedure details */
        200: {
          content: never;
        };
      };
    };
    /** Update procedure */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Procedure"];
        };
      };
      responses: {
        /** @description Procedure updated */
        200: {
          content: never;
        };
      };
    };
    /** Delete procedure */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Procedure deleted */
        204: {
          content: never;
        };
      };
    };
  };
  "/api/v1/roles": {
    /** List all roles with permissions */
    get: {
      responses: {
        /** @description List of roles */
        200: {
          content: never;
        };
      };
    };
    /** Create role */
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            description?: string;
            permissionIds?: string[];
          };
        };
      };
      responses: {
        /** @description Role created */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/roles/{id}": {
    /** Update role */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            name?: string;
            description?: string;
            permissionIds?: string[];
          };
        };
      };
      responses: {
        /** @description Role updated */
        200: {
          content: never;
        };
      };
    };
    /** Delete role */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Role deleted */
        204: {
          content: never;
        };
      };
    };
  };
  "/api/v1/permissions": {
    /** List all permissions */
    get: {
      responses: {
        /** @description List of permissions */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/search": {
    /** Global search across incidents, procedures, systems */
    get: {
      parameters: {
        query: {
          /** @description Search query */
          q: string;
        };
      };
      responses: {
        /** @description Search results grouped by entity type */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/email-templates": {
    /** Get all email templates */
    get: {
      responses: {
        /** @description List of templates */
        200: {
          content: {
            "application/json": components["schemas"]["EmailTemplate"][];
          };
        };
      };
    };
  };
  "/api/v1/email-templates/{id}": {
    /** Get email template details */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Template details */
        200: {
          content: never;
        };
      };
    };
    /** Update email template */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            subject?: string;
            /** @description HTML body with template variables like {{incident.title}} */
            body?: string;
            enabled?: boolean;
            cc?: string;
          };
        };
      };
      responses: {
        /** @description Template updated */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/email-templates/preview": {
    /** Preview rendered email template */
    post: {
      requestBody: {
        content: {
          "application/json": {
            body?: string;
            variables?: Record<string, never>;
          };
        };
      };
      responses: {
        /** @description Preview HTML generated */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/config/smtp": {
    /** Get SMTP configuration (passwords masked) */
    get: {
      responses: {
        /** @description Current SMTP config */
        200: {
          content: never;
        };
      };
    };
    /** Update SMTP configuration */
    put: {
      requestBody: {
        content: {
          "application/json": {
            host?: string;
            port?: number;
            secure?: boolean;
            user?: string;
            pass?: string;
            from?: string;
          };
        };
      };
      responses: {
        /** @description SMTP config updated */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/config/smtp/test": {
    /** Send test email with current SMTP config */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: email
             * @description Email address to send the test to
             */
            email: string;
          };
        };
      };
      responses: {
        /** @description Test email sent successfully */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/config/params": {
    /** Get all system parameters */
    get: {
      responses: {
        /** @description Key-value pairs of system configuration */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/config/{key}": {
    /** Update a system config value */
    put: {
      parameters: {
        path: {
          /** @description Configuration key name */
          key: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            value: string;
          };
        };
      };
      responses: {
        /** @description Config value updated */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/audit-logs": {
    /** Get audit logs (paginated) */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
          /** @description Filter by action type */
          actionType?: string;
          /** @description Filter by entity type */
          entityType?: string;
          /** @description Filter by user ID */
          userId?: string;
        };
      };
      responses: {
        /** @description List of audit logs */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/planning/instances": {
    /** List planning instances */
    get: {
      responses: {
        /** @description List of planning instances */
        200: {
          content: never;
        };
      };
    };
    /** Create planning instance */
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
          };
        };
      };
      responses: {
        /** @description Planning instance created */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/planning/instances/{id}": {
    /** Get planning instance details */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Instance details with jobs */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/planning/instances/{id}/archive": {
    /** Archive a planning instance */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Instance archived */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/planning/instances/{id}/reactivate": {
    /** Reactivate an archived instance */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Instance reactivated */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/planning/instances/{id}/jobs": {
    /** Get jobs for a planning instance */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description List of jobs in this instance */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/planning/jobs": {
    /** Create a planning job */
    post: {
      requestBody: {
        content: {
          "application/json": {
            instanceId: string;
            jobId: string;
            position?: number;
          };
        };
      };
      responses: {
        /** @description Planning job created */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/planning/jobs/{id}": {
    /** Update a planning job */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            status?: string;
            position?: number;
          };
        };
      };
      responses: {
        /** @description Planning job updated */
        200: {
          content: never;
        };
      };
    };
    /** Delete a planning job */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Planning job deleted */
        204: {
          content: never;
        };
      };
    };
  };
  "/api/v1/planning/jobs/{id}/status": {
    /** Update planning job status */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            status: string;
          };
        };
      };
      responses: {
        /** @description Job status updated */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/planning/jobs/{id}/complete": {
    /** Mark planning job as complete */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Job marked complete */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/planning/jobs/{id}/position": {
    /** Update job position (drag-and-drop reorder) */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            position: number;
          };
        };
      };
      responses: {
        /** @description Job position updated */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/planning/jobs/positions/batch": {
    /** Batch update job positions */
    patch: {
      requestBody: {
        content: {
          "application/json": {
            updates?: {
                id?: string;
                position?: number;
              }[];
          };
        };
      };
      responses: {
        /** @description Positions updated */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/analytics/mttr": {
    /** Get Mean Time To Resolution trends */
    get: {
      parameters: {
        query?: {
          /** @description Number of days to analyze */
          days?: number;
        };
      };
      responses: {
        /** @description MTTR trend data */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/analytics/sla-compliance": {
    /** Get SLA compliance metrics */
    get: {
      parameters: {
        query?: {
          days?: number;
        };
      };
      responses: {
        /** @description SLA compliance data */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/analytics/team-performance": {
    /** Get team performance metrics */
    get: {
      parameters: {
        query?: {
          days?: number;
        };
      };
      responses: {
        /** @description Team performance data */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/analytics/severity": {
    /** Get severity distribution */
    get: {
      parameters: {
        query?: {
          days?: number;
        };
      };
      responses: {
        /** @description Severity distribution data */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/auto-assign-rules": {
    /** List auto-assignment rules */
    get: {
      responses: {
        /** @description List of rules */
        200: {
          content: never;
        };
      };
    };
    /** Create auto-assignment rule */
    post: {
      requestBody: {
        content: {
          "application/json": {
            systemId?: string;
            severity?: string;
            assignToUserId?: string;
            teamId?: string;
            isActive?: boolean;
          };
        };
      };
      responses: {
        /** @description Rule created */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/auto-assign-rules/{id}": {
    /** Update auto-assignment rule */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["AutoAssignmentRule"];
        };
      };
      responses: {
        /** @description Rule updated */
        200: {
          content: never;
        };
      };
    };
    /** Delete auto-assignment rule */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Rule deleted */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/escalation-rules": {
    /** List escalation rules */
    get: {
      responses: {
        /** @description List of escalation rules */
        200: {
          content: never;
        };
      };
    };
    /** Create escalation rule */
    post: {
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            severity?: string;
            triggerAfterMinutes?: number;
            escalateToUserId?: string;
            isActive?: boolean;
          };
        };
      };
      responses: {
        /** @description Rule created */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/escalation-rules/{id}": {
    /** Update escalation rule */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["EscalationRule"];
        };
      };
      responses: {
        /** @description Rule updated */
        200: {
          content: never;
        };
      };
    };
    /** Delete escalation rule */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Rule deleted */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/webhooks": {
    /** List webhooks */
    get: {
      responses: {
        /** @description List of webhooks */
        200: {
          content: never;
        };
      };
    };
    /** Create webhook */
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** Format: uri */
            url: string;
            /** @description Comma-separated event types */
            events: string;
            isActive?: boolean;
            secret?: string;
          };
        };
      };
      responses: {
        /** @description Webhook created */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/webhooks/{id}": {
    /** Update webhook */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Webhook"];
        };
      };
      responses: {
        /** @description Webhook updated */
        200: {
          content: never;
        };
      };
    };
    /** Delete webhook */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Webhook deleted */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/webhooks/{id}/deliveries": {
    /** Get webhook delivery history */
    get: {
      parameters: {
        query?: {
          /** @description Number of deliveries to return */
          limit?: number;
        };
        path: {
          id: string;
        };
      };
      responses: {
        /** @description List of webhook deliveries */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Incident: {
      id?: string;
      title?: string;
      description?: string;
      /** @enum {string} */
      severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
      /** @enum {string} */
      status?: "Open" | "In Progress" | "Acknowledged" | "Resolved" | "Closed";
      environment?: string;
      systemId?: string;
      sysout?: string;
      assignedToId?: string;
      createdById?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    System: {
      id?: string;
      name?: string;
      description?: string;
    };
    EmailTemplate: {
      id?: string;
      name?: string;
      subject?: string;
      body?: string;
      variables?: string;
      enabled?: boolean;
      cc?: string;
    };
    Job: {
      id?: string;
      name?: string;
      code?: string;
      systemId?: string;
      teamId?: string;
    };
    Team: {
      id?: string;
      name?: string;
      description?: string;
      emailDistribution?: string;
      isActive?: boolean;
      sendEmail?: boolean;
    };
    SLA: {
      id?: string;
      name?: string;
      /** @enum {string} */
      severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
      acknowledgeTimeMinutes?: number;
      resolveTimeMinutes?: number;
    };
    User: {
      id?: string;
      name?: string;
      email?: string;
      roleId?: string;
      isActive?: boolean;
    };
    Role: {
      id?: string;
      name?: string;
      description?: string;
    };
    Permission: {
      id?: string;
      code?: string;
      description?: string;
    };
    AuditLog: {
      id?: string;
      actionType?: string;
      entityType?: string;
      entityId?: string;
      userId?: string;
      details?: string;
      /** Format: date-time */
      timestamp?: string;
    };
    Procedure: {
      id?: string;
      title?: string;
      content?: string;
      systemId?: string;
    };
    AutoAssignmentRule: {
      id?: string;
      systemId?: string;
      severity?: string;
      assignToUserId?: string;
      teamId?: string;
      isActive?: boolean;
    };
    EscalationRule: {
      id?: string;
      name?: string;
      severity?: string;
      triggerAfterMinutes?: number;
      escalateToUserId?: string;
      isActive?: boolean;
    };
    Webhook: {
      id?: string;
      name?: string;
      url?: string;
      events?: string;
      isActive?: boolean;
      secret?: string;
    };
    PlanningInstance: {
      id?: string;
      name?: string;
      /** Format: date-time */
      startDate?: string;
      /** Format: date-time */
      endDate?: string;
      status?: string;
      isArchived?: boolean;
    };
    PlanningJob: {
      id?: string;
      instanceId?: string;
      jobId?: string;
      status?: string;
      position?: number;
    };
    ApiResponse: {
      success?: boolean;
      data?: Record<string, never>;
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
